-- MySQL Script generated by MySQL Workbench
-- Wed May 26 23:15:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TEST` ;

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEST` DEFAULT CHARACTER SET utf8 ;
USE `TEST` ;

-- -----------------------------------------------------
-- Table `TEST`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`books` ;

CREATE TABLE IF NOT EXISTS `TEST`.`books` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `author` VARCHAR(120) NOT NULL,
  `publisher` VARCHAR(120) NOT NULL,
  `country` VARCHAR(120) NOT NULL,
  `price` DECIMAL(10,2) NULL,
  `currency` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;